### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Yixuan39**
fix problems in 2nd pull request

### CODE REVIEW

**Review by xji3 — CHANGES_REQUESTED** [review]
Could you redo your changes to `CodonGeneconv.py`?  I cannot find them.

**Comment by xji3** [comment]
A good practice is to review your code changes with `git diff FILE_NAME` before you commit them

**Comment by Yixuan39** [comment]
> Could you redo your changes to `CodonGeneconv.py`? I cannot find them.

Hello Xiang, I think I make all changes on CodonGeneconv.py. I think there's one commit shows I delete everything, because I accidentally click rollback in pycharm, but I then change the head to previous commit.

**Comment by xji3** [comment]
Then, just fix it.  Try to redo/remove that commit.

**Pull request closed without merging**
